// Hikâye: karakterler, sahneler ve bölge görevlerinin başlık/açıklamaları. Saf veri, DOM yok.
//
// Sahne kimlikleri:
//   giris, ogretici            oyunun açılışı ve öğretici sonu
//   <bolge>-<n>                bölgenin n. görevi (1 tabanlı) alındıktan sonra (varsa)
//   <bolge>-acik, <bolge>-giris bölge seviyeyle açıldığında / ilk girişte
//   prestij-hazir, prestij     prestij açıldığında / her prestijden sonra
// Satır: [kişi, metin]. Kişiler KISILER'de; 'mektup' portresiz mektup kartıdır.

export const KISILER = Object.freeze({
  sen: { ad: 'Sen', unvan: 'Ocak Sahibi', resim: 'img/ref/avatar.png' },
  ahmet: { ad: 'Ahmet Yılmaz', unvan: 'Maden Mühendisi', resim: 'img/ref/yuz-0.png' },
  elif: { ad: 'Elif Çelik', unvan: 'Lojistik Uzmanı', resim: 'img/ref/yuz-1.png' },
  mehmet: { ad: 'Mehmet Kara', unvan: 'Finans Uzmanı', resim: 'img/ref/yuz-2.png' },
  zeynep: { ad: 'Zeynep Arslan', unvan: 'Jeolog, Araştırmacı', resim: 'img/ref/yuz-3.png' },
  selim: { ad: 'Selim Demirhan', unvan: 'Demirhan Holding', resim: null, tohum: 7351 },
  mektup: { ad: "Kâzım Dede'nin Mektubu", unvan: 'Eski bir zarf', resim: null },
})

export const BOLUMLER = Object.freeze([
  { bolge: 'zonguldak', no: 1, ad: 'Dedemin Ocağı' },
  { bolge: 'eregli', no: 2, ad: 'Demir ve Liman' },
  { bolge: 'karabuk', no: 3, ad: 'Taş ve Ray' },
  { bolge: 'kastamonu', no: 4, ad: 'Bakırın Kalbi' },
])

// Görev yazıları: [başlık, açıklama, sahne var mı]
const G = (baslik, aciklama, sahne = false) => Object.freeze({ baslik, aciklama, sahne })

export const GOREV_YAZI = Object.freeze({
  zonguldak: Object.freeze([
    G('Ocağı Uyandır', 'Paslı kazmalar yeniden parlamalı.', true),
    G('İlk Ustabaşı', 'Bir yönetici, sen yokken de ocağı çalıştırır.', true),
    G('Derine İn', 'Eski haritalarda bir kat daha görünüyor.', true),
    G('Kabin Ustası', 'Asansör kendi kendine çalışsın.'),
    G('Vagon Başı', 'Yükleme katında satış hiç durmasın.', true),
    G('Damarın İzinde', 'Kademe ödülleri üretimi katlar.', true),
    G('Usta Hüneri', 'Yöneticinin yeteneği ocağı hızlandırır.', true),
    G('Grizu Kapısı', 'Derin katlarda havalandırma şart.', true),
    G('Çelik Halatlar', 'Kabin daha çok, daha hızlı taşısın.', true),
    G('İlk Kontrat', 'Bir müşterinin siparişini teslim et.', true),
    G('Dedenin Kazmadığı Kat', 'Kâzım Usta bile bu derinliğe inmemişti.', true),
    G('Kasabanın Ekmeği', 'Depoyu büyüt, kasabaya daha çok iş.', true),
    G('Zonguldak Limanı', 'Kömür gemilerle Karadeniz\'e açılsın.', true),
    G('Kara Elmas', 'En kaliteli kömür en dipte.', true),
    G("Zonguldak'ın Yeniden Doğuşu", 'Bölgenin bütün damarlarını işlet.', true),
  ]),
  eregli: Object.freeze([
    G('Paslı Raylar', 'Demir ocağının ilk katını canlandır.'),
    G('Liman İşçileri', "Ereğli'de ilk yöneticini tut.", true),
    G('Kızıl Damar', 'Demir cevheri derinlerde koyulaşıyor.', true),
    G('Vinç Operatörü', 'Asansöre bir usta lazım.'),
    G('Rıhtım Şefi', 'Depo ve vagonlar kendi işlesin.', true),
    G('Dövülmüş Çelik', 'Üretimi kademe ödülüyle katla.'),
    G('Fırtına Vardiyası', 'Bir yöneticinin yeteneğini kullan.', true),
    G('Deniz Altındaki Galeri', 'Galeriler denizin altına uzanıyor.', true),
    G('Yüksek Fırın', 'Asansör yükü fabrikaya yetişsin.'),
    G('Çelik Fabrikası Siparişi', "Ereğli'de bir kontrat tamamla.", true),
    G('Demirin Kalbi', 'En saf demir en derinde.', true),
    G('Rıhtım Genişlemesi', 'Depo kapasitesini büyüt.'),
    G('Ereğli Limanını Tamamla', "Ereğli'deki liman altyapısını geliştir.", true),
    G('Gemi Sözleşmesi', 'Yeni katlar, yeni gemiler.', true),
    G("Karadeniz'in Demiri", "Ereğli'nin bütün damarlarını işlet.", true),
  ]),
  karabuk: Object.freeze([
    G('İlk Blok', 'Ocaktan ilk taş bloğu çıkar.', true),
    G('Taşçı Ustası', "Karabük'te ilk yöneticini tut."),
    G('Andezit Basamağı', 'Ocağın yeni basamağını aç.', true),
    G('Kaldıraç ve Kasnak', 'Ağır blokları asansör taşısın.'),
    G('Ray Başı', 'Taş vagonları kendi işlesin.', true),
    G('Safranbolu Restorasyonu', 'Tarihî evler için taş üret.', true),
    G('Ustanın Kaması', 'Bir yöneticinin yeteneğini kullan.'),
    G('Köprü Ayakları', 'Demiryolu köprüsü için daha derine in.', true),
    G('Ağır Yük Kabini', 'Asansörü güçlendir.'),
    G('Demiryolu Kontratı', "Karabük'te bir kontrat tamamla.", true),
    G('Sabotaj Gecesi', 'Yeni kat aç, işler aksamasın.', true),
    G('Ray Deposu', 'Depoyu büyüt, raylara yetiş.'),
    G('Kuru Liman', "Karabük'e bir tren terminali kur.", true),
    G('Taş Köprü', 'Köprü tamamlanmak üzere.', true),
    G('Karadeniz Demiryolu', "Karabük'ün bütün basamaklarını işlet.", true),
  ]),
  kastamonu: Object.freeze([
    G('Roma Galerisi', 'Antik galerilerin yanında ilk katı güçlendir.', true),
    G('Dağ Kılavuzu', "Kastamonu'da ilk yöneticini tut."),
    G('Yeşil Damar', 'Malakit izlerini takip et.', true),
    G('Dağ Asansörü', 'Asansöre usta tut.'),
    G('Orman Yolu', 'Depo vagonları kendi işlesin.', true),
    G('Saf Bakır', 'Kademe ödülüyle üretimi katla.', true),
    G('Ustaların Gecesi', 'Bir yöneticinin yeteneğini kullan.'),
    G("Selim'in Sırrı", 'Daha derine in.', true),
    G('Kablo Fabrikası', 'Asansör yükü fabrikaya yetişsin.'),
    G('Elektrik Kontratı', "Kastamonu'da bir kontrat tamamla.", true),
    G('Kooperatif', 'Yeni katlar, yeni ortaklar.', true),
    G('Bakır Deposu', 'Depoyu büyüt.'),
    G('İnebolu Limanı', "Bakırı İnebolu'dan dünyaya gönder.", true),
    G('Dağın Kalbi', 'Bakırın kalbine yaklaş.', true),
    G("Karadeniz'in Madencisi", "Kastamonu'nun bütün damarlarını işlet.", true),
  ]),
})

const S = (baslik, ...satirlar) => Object.freeze({ baslik, satirlar: Object.freeze(satirlar) })

export const SAHNELER = Object.freeze({
  // ── Bölüm 1: Zonguldak ──
  giris: S('Dedemin Ocağı',
    ['mektup', 'Sevgili torunum, bu mektubu okuyorsan ben artık aranızda değilim. Zonguldak\'taki ocağımız yıllardır kapalı. Kasabanın yarısı bir zamanlar o ocaktan ekmek yerdi.'],
    ['mektup', 'Anahtarları Ahmet\'e bıraktım. Ocağı yeniden aç, kasabaya hayat ver. Unutma: kömür karadır ama alın teri aktır. — Kâzım Dede'],
    ['ahmet', 'Hoş geldin! Ben Ahmet, maden mühendisiyim. Babam deden Kâzım Usta\'nın yanında yetişti. Ocak eski ama damarlar hâlâ zengin.'],
    ['ahmet', 'İlk kat hazır, bir de cesur bir madencimiz var. Önce onu yükseltelim, sonra kazmaya başlarız!'],
  ),
  ogretici: S('Ocak Uyandı',
    ['ahmet', 'İşte bu! Kazma vuruyor, asansör çıkıyor, depo satıyor. Ocağın düdüğünü bütün kasaba duydu.'],
    ['mehmet', 'Merhaba, ben Mehmet Kara. Bankadaki işimi bıraktım; deden zor günümde bana sahip çıkmıştı. Hesap kitap işleri artık bende.'],
    ['mehmet', 'Bir önerim var: Harita sekmesindeki görevleri takip et. Her görev ocağı büyütür, kasaya da elmas getirir.'],
  ),
  'zonguldak-1': S('Kahvede Konuşulanlar',
    ['ahmet', 'Kazmalar keskinleşti! Kasabanın yaşlıları kahvede "Kâzım Usta\'nın ocağı geri döndü" diye konuşuyormuş.'],
  ),
  'zonguldak-2': S('Alın Teri',
    ['mehmet', 'Yönetici tutmak akıllıcaydı. Biz uyurken bile ocak çalışacak.'],
    ['mehmet', 'Paramızı faize değil, alın terine yatırıyoruz. Deden de böyle yapardı.'],
  ),
  'zonguldak-3': S('Önce Güvenlik',
    ['ahmet', 'Yeni kat açıldı! Yalnız dikkat: derinlere indikçe grizu riski artar. Havalandırmayı her vardiya kontrol edeceğim.'],
    ['sen', 'Güvenlik her şeyden önce gelir, Ahmet. Bu ocakta kimse yaralanmayacak.'],
  ),
  'zonguldak-5': S('Elif Geliyor',
    ['elif', 'Merhaba! Ben Elif Çelik, lojistik uzmanıyım. İstanbul\'da büyük bir firmadaydım ama memleketim burası.'],
    ['elif', 'Ocağın döndüğünü duyunca dayanamadım. Vagonlar, raylar, limanlar... Taşıma işleri artık bende!'],
  ),
  'zonguldak-6': S('Eski Haritalar',
    ['zeynep', 'Selam! Zeynep Arslan, jeoloğum. Üniversitenin arşivinde bu ocağın 1950\'lerden kalma haritalarını buldum.'],
    ['zeynep', 'Haritalara göre aşağıda çok daha zengin damarlar var. Araştırma laboratuvarını kurarsak onlara daha hızlı ulaşırız.'],
  ),
  'zonguldak-7': S('Ocak Başı',
    ['ahmet', 'Ustaların hünerlerini kullanmayı öğrendin. Artık gerçek bir ocak başısın!'],
  ),
  'zonguldak-8': S('Bir Teklif',
    ['selim', 'İyi günler. Selim Demirhan, Demirhan Holding. Ocağınızın yeniden açıldığını duydum. Tebrikler... gerçekten.'],
    ['selim', 'Size cömert bir teklifim var: ocağı bana satın, rahatınıza bakın. Bu işler küçük girişimcilere göre değil.'],
    ['sen', 'Bu ocak dedemin emaneti. Satılık değil.'],
    ['mehmet', 'Demirhan Holding... Karadeniz\'deki kapalı madenlerin çoğunu ucuza toplayıp hiç açmadılar. Gözümüzü dört açalım.'],
  ),
  'zonguldak-9': S('Tıkır Tıkır',
    ['elif', 'Asansör artık saatte yüzlerce ton taşıyor. Halatları çelikle değiştirdim, kabin tıkır tıkır!'],
  ),
  'zonguldak-10': S('İlk Müşteri',
    ['elif', 'İlk kontratı teslim ettik! Ereğli\'deki çelik fabrikası kömürümüzün kalitesine bayılmış.'],
    ['mehmet', 'Kontratlar düzenli gelir demek. Bankadan kredi istemeye bile gerek kalmadı.'],
  ),
  'zonguldak-11': S('Dedenin Kazmadığı Kat',
    ['ahmet', 'Bu derinliğe deden bile inmemişti. Seninle gurur duyardı, eminim.'],
    ['zeynep', 'Kayaçlar değişiyor... Burada başka bir şey var. Numuneleri laboratuvara götürüyorum.'],
  ),
  'zonguldak-12': S('Fırıncının Sözü',
    ['mehmet', 'Kasabada yüz kişiye iş verdik! Fırıncı bile "ocak açılınca ekmek iki kat satıyor" diyor.'],
  ),
  'zonguldak-13': S('Gemiler Yola Çıkıyor',
    ['elif', 'Zonguldak limanı yeniden canlandı. Kömürümüz artık gemilerle bütün Karadeniz\'e gidiyor.'],
    ['selim', 'Liman işine de mi girdiniz? Bakalım ne kadar dayanacaksınız...'],
  ),
  'zonguldak-14': S('Numunelerin Sırrı',
    ['zeynep', 'Numunelerin sonucu geldi: Ereğli kıyısında yüksek tenörlü demir cevheri var! Ama oranın ruhsatını Demirhan da istiyor.'],
    ['mehmet', 'O zaman acele etmeliyiz. Seviyen 15 olunca Ereğli ruhsatını alabiliriz.'],
  ),
  'zonguldak-15': S('Zonguldak Bayramı',
    ['ahmet', 'Zonguldak\'ın bütün damarları işliyor. Kasabada bayram havası var!'],
    ['mehmet', 'Bölge Ustası unvanını aldın: Zonguldak\'taki bütün satışlar kalıcı olarak %10 arttı.'],
    ['sen', 'Bu daha başlangıç. Dedemin hayali bütün Karadeniz\'di.'],
  ),

  // ── Bölüm 2: Ereğli ──
  'eregli-acik': S('Ruhsat Bizde',
    ['elif', 'Haberler iyi: Ereğli demir ocağının ruhsatı bizim! Üstelik eski bir iskelesi de var.'],
    ['elif', 'Demirhan limanı kapatmak istiyordu ama geç kaldı. Harita sekmesinden Ereğli\'ye geçebilirsin.'],
  ),
  'eregli-giris': S('Demirin Kıyısı',
    ['elif', 'Ereğli\'ye hoş geldin! Burası denizle demirin buluştuğu yer. Ocak bakımsız ama iskele sağlam.'],
    ['ahmet', 'Demir cevheri kömürden serttir; kazmaları değiştirdim. Yine ilk kattan başlıyoruz!'],
    ['mehmet', 'Bölgelerin kasaları ayrı. Zonguldak\'ın yöneticili katları sen buradayken de kazanmaya devam eder.'],
  ),
  'eregli-2': S('Liman İşçileri',
    ['elif', 'Liman işçileri bizi bekliyormuş. "Demirhan iskeleyi kapatsaydı hepimiz işsiz kalırdık" diyorlar.'],
  ),
  'eregli-3': S('Kızıl Damar',
    ['zeynep', 'Kızıl damar! Hematit bu, hem de çok saf. Laboratuvarda yeni bir alaşım denemesi yapacağım.'],
  ),
  'eregli-5': S('Gece Gündüz',
    ['elif', 'Rıhtım artık gece gündüz çalışıyor. Vagonlar dolup boşalıyor, vinçler hiç durmuyor.'],
  ),
  'eregli-7': S('Kapanan Yol',
    ['selim', 'Ereğli\'de de mi? Limanın girişindeki arsayı satın aldım. Gemileriniz dolaşmak zorunda kalacak.'],
    ['elif', 'Dolaşırız, Selim Bey. Biz yolu uzatmayı biliriz; kısaltmayı da öğreniriz.'],
  ),
  'eregli-8': S('Denizin Altında',
    ['ahmet', 'Galeriler denizin altına uzanıyor. Su sızıntısına karşı pompaları iki katına çıkardım.'],
  ),
  'eregli-10': S('Kendi Zincirimiz',
    ['mehmet', 'Ereğli Çelik Fabrikası ilk siparişini aldı. Kömür Zonguldak\'tan, demir Ereğli\'den: kendi tedarik zincirimizi kurduk!'],
  ),
  'eregli-11': S('Ceneviz Tüneli',
    ['zeynep', 'Burada eski bir Ceneviz tüneli bulduk! Tarihçiler çok heyecanlandı. Tüneli müzeye çevirelim mi?'],
    ['sen', 'Elbette. Bu kıyının hikâyesi bizden çok daha eski.'],
  ),
  'eregli-13': S('Kendi Rıhtımımız',
    ['elif', 'Ereğli Limanı tamamlandı! Artık Demirhan\'ın arsasına ihtiyacımız yok; kendi rıhtımımızdan yükleme yapıyoruz.'],
    ['selim', '...Etkileyici. Ama Karabük\'te işler o kadar kolay olmayacak.'],
  ),
  'eregli-14': S('Uzak Limanlar',
    ['mehmet', 'Bir gemi şirketi uzun vadeli sözleşme istiyor. Ereğli artık Karadeniz\'in yıldızı.'],
  ),
  'eregli-15': S('Düdükler Çalıyor',
    ['elif', 'Ereğli tamam! Limanda bayram var, gemiler düdük çalıyor.'],
    ['mehmet', 'İkinci Bölge Ustası unvanın hayırlı olsun: Ereğli satışları kalıcı %10 arttı.'],
    ['zeynep', 'Sıradaki hedef Karabük. Oradaki taş ocakları demiryolunu yeniden kurmamız için şart.'],
  ),

  // ── Bölüm 3: Karabük ──
  'karabuk-acik': S('Tapu Bizde',
    ['ahmet', 'Karabük\'teki eski taş ocağı satışa çıkmış. Demirhan\'dan önce davrandık, tapu bizde!'],
    ['elif', 'Karabük taşıyla demiryolunu onarırsak kömür, demir ve taş aynı hatta akar. Harita\'dan Karabük\'e geçebilirsin.'],
  ),
  'karabuk-giris': S('Taşın Şehri',
    ['ahmet', 'Karabük\'e hoş geldin! Burası taş ocağı; kazmanın yanında kırıcı ve kama da kullanacağız.'],
    ['zeynep', 'Bu taş andezit. Safranbolu\'nun tarihî evlerinin temelleri de bu taştan. Restorasyon için çok değerli.'],
  ),
  'karabuk-1': S('Meydandaki Blok',
    ['ahmet', 'İlk blok çıktı! İşçiler onu hatıra olarak kasaba meydanına koymak istiyor.'],
  ),
  'karabuk-3': S('Andezit',
    ['zeynep', 'Andezit katmanları çok düzenli. Sertliği demiryolu traversleri için mükemmel.'],
  ),
  'karabuk-5': S('İlk Sevkiyat',
    ['elif', 'Taş vagonları raylara dizildi. Zonguldak–Karabük hattı için ilk sevkiyat yolda!'],
  ),
  'karabuk-6': S('Tarihe Yatırım',
    ['mehmet', 'Safranbolu Belediyesi restorasyon için bizden taş istedi. Tarihi korurken kazanmak... buna yatırım derim.'],
  ),
  'karabuk-8': S('Sağlam Temel',
    ['ahmet', 'Köprü ayakları için en sağlam taş en derinde. Mühendislik hesaplarını üç kez kontrol ettim.'],
  ),
  'karabuk-10': S('Raylar Uzanıyor',
    ['elif', 'Demiryolu idaresiyle kontrat imzalandı! Raylar Zonguldak\'tan Karabük\'e uzanacak.'],
  ),
  'karabuk-11': S('Sabotaj Gecesi',
    ['ahmet', 'Dün gece birileri asansör halatlarını kesmeye çalışmış! Bekçiler kaçarken görmüş.'],
    ['mehmet', 'Kamera kayıtlarında Demirhan Holding\'in kamyoneti var. Savcılığa başvurdum.'],
    ['sen', 'Kimse yaralanmadı ya? Önemli olan bu. Güvenliği iki katına çıkaralım.'],
  ),
  'karabuk-13': S('Kuru Liman',
    ['elif', 'Karabük Kuru Limanı açıldı! Trenler artık doğrudan Ereğli rıhtımına bağlanıyor.'],
  ),
  'karabuk-14': S('Beklenmedik Ziyaret',
    ['selim', 'Savcılık... Bunu ben istemedim. Holdingde bazı yöneticiler kontrolden çıktı.'],
    ['selim', 'Sizinle konuşmam gereken şeyler var. Ama burada değil. Kastamonu\'da.'],
  ),
  'karabuk-15': S('İlk Tren',
    ['ahmet', 'Karabük tamamlandı! Taş köprü bitti, ilk tren düdüğünü çaldı.'],
    ['mehmet', 'Üçüncü Bölge Ustası! Karabük satışları kalıcı %10 arttı.'],
    ['zeynep', 'Ve sıradaki durak... Kastamonu. Küre\'deki bakır damarları. Ölçümlerim çıldırıyor!'],
  ),

  // ── Bölüm 4: Kastamonu ──
  'kastamonu-acik': S('Açık Artırma',
    ['zeynep', 'Küre\'deki eski bakır madeninin ruhsatı açık artırmaya çıktı. Mehmet bütün birikimimizi ortaya koydu ve kazandık!'],
    ['mehmet', 'Bir de sürpriz var: Selim Demirhan açık artırmadan son anda çekildi. Neden acaba?'],
  ),
  'kastamonu-giris': S('Küre Dağları',
    ['zeynep', 'Küre\'ye hoş geldin! Bu dağlarda bakır binlerce yıldır çıkarılıyor; Romalılar bile burada kazmış.'],
    ['ahmet', 'Bakır cevheri yeşil ve turuncu damarlarla parlıyor. Bu ocak hepsinden zengin, ama hepsinden de derin.'],
  ),
  'kastamonu-1': S('Roma Galerisi',
    ['zeynep', 'Roma dönemi galerileri hâlâ ayakta! Arkeologlarla birlikte çalışacağız; tarihi koruyarak kazacağız.'],
  ),
  'kastamonu-3': S('Malakit',
    ['zeynep', 'Yeşil damar: malakit! Bakırın en güzel hâli. Laboratuvarda daha verimli bir ayrıştırma yöntemi buldum.'],
  ),
  'kastamonu-5': S('Ağaçların Arasından',
    ['elif', 'Orman yolundan geçen vagonlar için ağaç kesmiyoruz; rayları ağaçların arasından dolaştırdım.'],
  ),
  'kastamonu-6': S('Rekor Fiyat',
    ['mehmet', 'Saf bakırın tonu rekor fiyattan satılıyor. Kasada hiç bu kadar para görmemiştim!'],
  ),
  'kastamonu-8': S("Selim'in Sırrı",
    ['selim', 'Geldiğiniz için teşekkür ederim. Bir itirafım var.'],
    ['selim', 'Yıllar önce babam, Kâzım Usta\'nın ocağını kapattırmak için sahte raporlar hazırlattı. Deden haksız yere her şeyini kaybetti.'],
    ['selim', 'Holdingi devraldığımda aynı hırsla devam ettim. Ama sizin ocaklarınızda insanlar yeniden gülümsüyor. Ben bunu hiç başaramadım.'],
    ['sen', 'Geçmişi değiştiremeyiz, Selim Bey. Ama gelecek için birlikte bir şeyler yapabiliriz.'],
  ),
  'kastamonu-10': S('Büyük Kontrat',
    ['mehmet', 'Türkiye\'nin en büyük kablo fabrikası bakırımızı istiyor. Bu kontrat bütün bölgelerin yükünü taşıyacak!'],
  ),
  'kastamonu-11': S('Kooperatif',
    ['mehmet', 'Bir fikrim var: Karadeniz Madenciler Kooperatifi! Her ocağın işçisi aynı zamanda ortağı olsun.'],
    ['selim', 'Demirhan Holding\'in kapalı ruhsatlarını kooperatife devretmek istiyorum. Babamın borcunu ancak böyle ödeyebilirim.'],
    ['ahmet', 'Kâzım Usta bunu duysaydı... Sevinçten ağlardı.'],
  ),
  'kastamonu-13': S('İnebolu Limanı',
    ['elif', 'İnebolu Limanı hazır! Bakırımız artık dünyanın dört bir yanına gidiyor.'],
  ),
  'kastamonu-14': S('Dağın Kalbi',
    ['zeynep', 'Ölçümler... inanılmaz. Bakırın kalbi hemen altımızda. Son kat da açılınca Karadeniz\'in en zengin madeni olacağız.'],
  ),
  'kastamonu-15': S('Karadeniz\'in Madencisi',
    ['ahmet', 'Başardık! Zonguldak\'tan Kastamonu\'ya, dört bölgenin bütün damarları işliyor.'],
    ['elif', 'Gemiler, trenler, vagonlar... Karadeniz\'in bütün yolları ocaklarımıza çıkıyor.'],
    ['mehmet', 'Kooperatifin üç bin ortağı var. Kâzım Usta\'nın kasabası artık bir bölgenin kalbi.'],
    ['zeynep', 'Ve bilim! Laboratuvarımız üç yeni patent aldı.'],
    ['selim', 'Kâzım Usta\'nın torunu... Babamın yıktığını sen onardın. Teşekkür ederim.'],
    ['mektup', 'Zarfın içinden ikinci bir not çıkıyor: "Bir gün bu satırları okursan bil ki seninle gurur duyuyorum. Kömür karadır ama alın teri aktır." — Kâzım Dede'],
  ),

  // ── Yeni Nesil ──
  'prestij-hazir': S('Yeni Nesil',
    ['ahmet', 'Bir fikrim var: Yeni Nesil! Ocakları gençlere devredip her şeyi baştan, daha güçlü kuralım. Deneyimimiz bizimle kalır.'],
    ['mehmet', 'Prestij yaparsan bölgeler sıfırlanır ama seviyen, elmasların ve araştırmaların kalır. Üstelik bütün satışlar kalıcı olarak artar.'],
  ),
  prestij: S('Yeniden Başlangıç',
    ['ahmet', 'Yeni nesil madenciler hazır! Ocakları ilk günkü gibi açıyoruz ama bu sefer her şey çok daha hızlı olacak.'],
  ),
})

// Görevin başlığı/açıklaması (bölge yoksa Zonguldak)
export function gorevYazi(bolge, i) {
  const l = GOREV_YAZI[bolge] || GOREV_YAZI.zonguldak
  return l[i] || null
}

// Görev i (0 tabanlı) alındıktan sonra oynayacak sahne kimliği ya da null
export function gorevSahnesi(bolge, i) {
  const y = gorevYazi(bolge, i)
  const id = bolge + '-' + (i + 1)
  return y && y.sahne && SAHNELER[id] ? id : null
}

// Sahnenin ait olduğu bölüm (hikâye defteri için)
export function sahneBolumu(id) {
  if (id === 'giris' || id === 'ogretici') return 'zonguldak'
  if (id.startsWith('prestij')) return 'prestij'
  return id.split('-')[0]
}
